//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mon
    {
        public string ID { get; set; }
        public string Tenmon { get; set; }
        public int Gia { get; set; }
        public string Ghichu { get; set; }
        public string Hinh { get; set; }
        public string Loai { get; set; }
        public string Diachi { get; set; }
        public string TP { get; set; }
    }
}
